name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
        
jobs:

  build-docker-proxy-acl:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Checkout Build Repo
        with:
          path: ./build
        
      - uses: actions/checkout@v2
      - name: Checkout App Repo
        with:
          repository: dcflachs/docker-proxy-acl
          path: ./app  
        
      - name: Get Git SHA
        id: sha
        shell: bash
        run: |
          cd ./app
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          cd ..
        
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
     
      - name: Login to DockerHub 
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Docker Repo
        id: repo
        run: echo "::set-output name=repo::dcflachs/docker-proxy-acl"
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./build/docker-proxy-acl
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7
          push: true
          labels: |
            `org.opencontainers.image.revision=${{ steps.sha.outputs.sha_short }}`
          tags: |
            ${{ steps.repo.outputs.repo }}:latest
            ${{ steps.repo.outputs.repo }}:nightly-${{ steps.date.outputs.date }}
            ${{ steps.repo.outputs.repo }}:sha-${{ steps.sha.outputs.sha_short }}
      
